### ISSUE TITLE
Install failed on MacOS catalina 10.15.4 Beta

### ISSUE THREAD

**Issue by rootsongjc** [ExistentialAudio/BlackHole#63]
I run this command to install BlackHole.

```bash
brew cask install blackhole
```

### Log

```
==> Purging files for version 0.2.6 of Cask blackhole
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=jimmysong USER=jimmysong USERNAME=jimmysong /usr/sbin/installer -pkg /usr/local/Caskroom/blackhole/0.2.6/BlackHole.v0.2.6.pkg -target /` exited with 1. Here's the output:
installer: Package name is BlackHole.v0.2.6
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “BlackHole.v0.2.6.pkg”.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
```

Set up with BlackHole.v0.2.6.pkg also failed.

![image](https://user-images.githubusercontent.com/3328185/75161237-729e4380-5756-11ea-8bb9-11c57fe8aeb6.png)

I have changed the Security & Privacy.

![image](https://user-images.githubusercontent.com/3328185/75161318-8a75c780-5756-11ea-8af5-cc4516eebf30.png)

**Comment by devinroth** [comment]
Thanks for reporting this. I think this is an issue with the Packages app that I used to create the installer. Maybe it no longer works on MacOS catalina 10.15.4 Beta and I'll have to use a different program. I'll look into it.

Have you been able to build and install BlackHole manually without issues?

**Comment by rootsongjc** [comment]
Although the installation stage failed, but I can see BlackHole 16ch on Audio Devices.

![image](https://user-images.githubusercontent.com/3328185/75207890-fbe46300-57b4-11ea-920c-6966a4987808.png)

**Comment by devinroth** [comment]
So it did install but something threw an error. Interesting. 

Devin

**Comment by aokie** [comment]
I have a similer issue. My case is nothing installed.
macOS 10.15.4 Beta（19E234g）

**Comment by devinroth** [comment]
Okay. I'll try to figure it out this week.

**Comment by aokie** [comment]
@devinroth 
I can install v0.2.6 to macOS 10.15.4 Beta（19E242d）successfully !

**Comment by devinroth** [comment]
Wow. Then maybe I don't need to do anything. I'll keep this up in case anything changes in future versions.

**Comment by devinroth** [comment]
I'm going to close. If the problem pops up again please reopen.

**Comment by sachit-n** [comment]
I have the exact same issue on Catalina 10.15.4
I cannot see blackhole in audio devices either.

**Comment by rootsongjc** [comment]
Finally, I choose to use Boom2 instead.

**Comment by sachit-n** [comment]
It worked for me after I updated to 10.15.5 from 10.15.4
